blueprint:
  name: taplinker_watering
  description: |
    A script that configures a TapLinker to water for the specified duration.
    
    **IMPORTANT: To prevent communication issues between Home Assistant, the gateway, and the TapLinker that could lead to the TapLinker not receiving the stop watering message in time—resulting in potential property damage—please set a reasonable watering duration (sensor.X_total_duration) or failsafe duration (sensor.X_failsafe_duration) for your TapLinker. For more details, check the documentation in the relevant sections: “Set watering duration (value of sensor.X_total_duration entity)” and “Set failsafe watering duration” (https://www.link-tap.com/#!/mqtt-and-home-assistant).**
    
    Please ensure that the entities used in a script belong to the same TapLinker device.
    
    The steps in this script are: 
    <ol>
        <li><p>Check the TapLinker's RF connection status. If offline, do nothing.</p></li>
        <li><p>Check the TapLinker's watering status. If already watering, stop the current process to save records.</p></li>
        <li><p>Turn on TapLinker's water switch and wait for the status to change to "on". Retry up to 3 times if it fails.</p></li>
        <li><p>Once the status is on, wait for the specified duration.</p></li>
        <li><p>After the duration, if the status is still "on", turn off the water switch. Retry up to 3 times if it fails.</p></li>
    </ol>
    
  domain: script
  source_url: https://github.com/jimlktwork/ha/blob/main/taplinker_watering.yaml
  input:
    taplinker_switch_entity:
      name: TapLinker Water Switch (switch.*_water_switch)
      description: The switch entity for controlling the TapLinker's valve.
      selector:
        entity:
          domain: switch
          multiple: false
    taplinker_watering_stat:
      name: TapLinker Watering Status (binary_sensor.*_is_watering)
      description: The binary sensor indicating if the TapLinker is currently watering.
      selector:
        entity:
          domain: binary_sensor
          multiple: false
    taplinker_rf_link_stat:
      name: TapLinker RF Connection Status (binary_sensor.*_is_rf_linked)
      description: The binary sensor indicating if the TapLinker is online.
      selector:
        entity:
          domain: binary_sensor
          device_class: connectivity
          multiple: false
    watering_duration:
      name: Watering Duration
      description: Duration (in seconds) for a single watering cycle. Ensure this is not greater than "sensor.X_total_duration" or "sensor.X_failsafe_duration", or the actual watering duration will be shorter than expected.
      default: 60
      selector:
        number:
          min: 3.0
          max: 86399.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
mode: single
sequence:
- if:
  - condition: state
    entity_id: !input taplinker_rf_link_stat
    state: 'on'
  then:
    - repeat:
        count: 3
        sequence:
          - if:
            - condition: state
              entity_id: !input taplinker_watering_stat
              state: 'on'
            then:
            - alias: Turn off the TapLinker first because it is already in watering
              service: switch.turn_off
              target:
                entity_id: !input taplinker_switch_entity
            - wait_for_trigger:
              - platform: state
                entity_id: !input taplinker_watering_stat
                from: 'on'
                to: 'off'
              continue_on_timeout: false
              timeout: '30'
    - repeat:
        count: 3
        sequence:
          - if:
            - condition: state
              entity_id: !input taplinker_watering_stat
              state: 'off'
            then:
            - alias: Turn on TapLinker
              service: switch.turn_on
              target:
                entity_id: !input taplinker_switch_entity
            - wait_for_trigger:
              - platform: state
                entity_id: !input taplinker_watering_stat
                from: 'off'
                to: 'on'
              continue_on_timeout: false
              timeout: '30'
    - delay: !input watering_duration
    - repeat:
        count: 3
        sequence:
          - if:
            - condition: state
              entity_id: !input taplinker_watering_stat
              state: 'on'
            then:
            - alias: Turn off the TapLinker
              service: switch.turn_off
              target:
                entity_id: !input taplinker_switch_entity
            - wait_for_trigger:
              - platform: state
                entity_id: !input taplinker_watering_stat
                from: 'on'
                to: 'off'
              continue_on_timeout: false
              timeout: '30'
